# Generated by Django 5.1.4 on 2024-12-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
