# Generated by Django 5.1.4 on 2024-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
